FROM python:3.12-slim

RUN apt-get update && apt-get install -y iputils-ping curl

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY products.py .

CMD ["python", "products.py"]
